### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by FireWizard52** [akamming/Domoticz_VolvoRecharge_Plugin#10]
Hi,

As you might know, I do not use your application in Domoticz, but Node-RED, but I take the freedom to contact you.

Today I discovered that after a reboot of my Raspberry Pi, needed because some other Node-RED nodes have been updated, I was not able to authorize anymore. The authorization procedure is equal for all applications, regardless, if it is for HA, Domoticz, OpenHab, IObroker, etc.

I received a statusCode 400 and an error message "unauthorized_client" 
This has been working for about a year, without a glitch
I'm afraid they closed a hole and authorizing with only username/password has been terminated.

Do you experience the same?

Regards

**Comment by akamming** [comment]
Hi,

No, but that's because i already builtin 2FA as an authorisation method. Volvo seems to have shutdown access without 2FA: My username/password testscript now indeed gives me an unauthorized_client. My 2fa testscript still works.

So you if you add 2FA, you should be fine again...

I built a seperate 2FA script to create the access token with 2FA and store it in an ini file. The volvo plugin then uses this ini to communicatie, maybe you can re-use it:

Domoticz_VolvoRecharge_Plugin/authorize.py at main · akamming/Domoticz_VolvoRecharge_Plugin (github.com)<https://github.com/akamming/Domoticz_VolvoRecharge_Plugin/blob/main/authorize.py>

Regards


________________________________
Van: FireWizard52 ***@***.***>
Verzonden: maandag 14 oktober 2024 16:29
Aan: akamming/Domoticz_VolvoRecharge_Plugin ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [akamming/Domoticz_VolvoRecharge_Plugin] Authorization (Issue #10)


Hi,

As you might know, I do not use your application in Domoticz, but Node-RED, but I take the freedom to contact you.

Today I discovered that after a reboot of my Raspberry Pi, needed because some other Node-RED nodes have been updated, I was not able to authorize anymore. The authorization procedure is equal for all applications, regardless, if it is for HA, Domoticz, OpenHab, IObroker, etc.

I received a statusCode 400 and an error message "unauthorized_client"
This has been working for about a year, without a glitch
I'm afraid they closed a hole and authorizing with only username/password has been terminated.

Do you experience the same?

Regards

**Comment by FireWizard52** [comment]
Hi,

Thank you very much for your response. Indeed my flow does not use 2FA (yet).
I will certainly look to your script that you made for 2FA. If I use it? We will see, as I can also make it in Node RED.
But anyhow, thanks for testing.

Regards
