### ISSUE TITLE
Revoke authorization?

### ISSUE THREAD

**Issue by nikagersonlohman** [akamming/Domoticz_VolvoRecharge_Plugin#12]
Anyone find a way to "revoke" the authorization? In my case the authorization flow returns:

1. USERNAME_PASSWORD_REQUIRED (after  /as/authorization.oauth2)
2. COMPLETED (after action=checkUsernamePassword)
3. An access_token (after token.oauth2)
4. But when using the access token it returns:

{
  "status" : 403,
  "operationId" : "1cbf623f-5516-4f96-acd2-a5f1d268d5ed",
  "error" : {
    "message" : "FORBIDDEN",
    "description" : "Access Denied"
  }
}

So the token returned somehow is incorrect. When I do the same from Postman, all is ok...

**Comment by nikagersonlohman** [comment]
A header in one of the other calls caused the access_token to be invalid (even though it was generated)

**Comment by akamming** [comment]
This is interesting. I only get "unathorized" when just using username/password. I needed to change the code to support 2FA.

Where is your working code with just username/password?

**Comment by nikagl** [comment]
No, I rewrote [your code](https://github.com/akamming/Domoticz_VolvoRecharge_Plugin/blob/main/authorize.py) in javascript/ecmascript for OpenHAB and was experimenting with the headers. I had authenticated once with the OTP and then it didn't require me to enter it anymore (hence my wish to reset the cookies), and I couldn't get it to authenticate with the OTP again. In the end it turned out it returned the (invalid) access token because I had left out certain headers... never asked me for OTP, but didn't work because of the bad access token...
